# Makefile 
# 
# Copyright(C)  2018 
# Contact: JeCortex@yahoo.com
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

OBJS = jradm.c JCreate.c jmdopen.c JManage.c
TGT = jradm
all:
	gcc $(OBJS) -o $(TGT)
clean:
	rm $(TGT)
